services:
  - type: web
    name: tours-backend
    env: node
    rootDirectory: backend_server
    buildCommand: npm install
    startCommand: node src/index.js  # Try this if your index.js is in a src folder
    # OR
    startCommand: node index.js      # Try this if index.js is in root
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false