services:
  - type: web
    name: tours-backend
    env: node
    rootDirectory: backend_server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true